import {
  Apartment,
  FloorPlan,
  ImageAsset,
  PriceHistoryPoint,
  ScrapeLog,
} from "@/lib/types";

const now = new Date();

export const floorPlans: FloorPlan[] = [
  {
    id: 1,
    name: "Traditional 1x1-758",
    beds: 1,
    baths: 1,
    sq_ft_min: 758,
    sq_ft_max: 758,
    description: "Cozy one-bedroom with updated kitchen finishes.",
  },
  {
    id: 2,
    name: "Traditional 2x2-1134",
    beds: 2,
    baths: 2,
    sq_ft_min: 1134,
    sq_ft_max: 1149,
    description: "Roommate-friendly two-bedroom layout.",
  },
  {
    id: 3,
    name: "Traditional 3x2.5-1552",
    beds: 3,
    baths: 2.5,
    sq_ft_min: 1552,
    sq_ft_max: 1647,
    description: "Townhome-style unit with optional attached garage.",
  },
];

export const apartments: Apartment[] = [
  {
    id: 101,
    unit_number: "B-312",
    floor_plan_id: 2,
    composite_key: "traditional-2x2-1134_2_2_1134_b-312",
    beds: 2,
    baths: 2,
    sq_ft: 1134,
    floor: 3,
    current_price: 1820,
    price_min: 1750,
    price_max: 1920,
    is_available: true,
    available_date: "Available Now",
    move_in_special: "Lease now for 6 weeks free!",
    lease_terms: "12 months",
    has_garage: false,
    has_fireplace: true,
    has_smart_home: true,
    is_renovated: true,
    is_top_floor: true,
    is_end_unit: false,
    has_sunroom: false,
    has_balcony: true,
    has_washer_dryer: true,
    view_type: "courtyard",
    feature_tags: [
      "Top Floor",
      "Wood Burning Fireplace",
      "Renovation Renewal Prog",
      "Courtyard View",
      "Smart Home Technology",
      "RENW Washer and Dryer",
    ],
    description:
      "Beautifully renovated unit with fireplace, courtyard view, and smart home package.",
    source: "maa",
    source_url: "https://www.maac.com/florida/tampa/maa-rocky-point/",
    first_seen_at: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    last_seen_at: new Date(now.getTime() - 1000 * 60 * 30).toISOString(),
    last_price_change_at: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: 102,
    unit_number: "A-204",
    floor_plan_id: 1,
    composite_key: "traditional-1x1-758_1_1_758_a-204",
    beds: 1,
    baths: 1,
    sq_ft: 758,
    floor: 2,
    current_price: 1685,
    price_min: 1600,
    price_max: 1720,
    is_available: true,
    available_date: "2026-02-20",
    move_in_special: "$500 look-and-lease bonus",
    lease_terms: "10-14 months",
    has_garage: false,
    has_fireplace: false,
    has_smart_home: true,
    is_renovated: true,
    is_top_floor: false,
    is_end_unit: true,
    has_sunroom: true,
    has_balcony: true,
    has_washer_dryer: true,
    view_type: "garden",
    feature_tags: ["Sunroom", "Garden View", "Smart Home Technology"],
    description: "Bright one-bedroom with sunroom and upgraded bath.",
    source: "maa",
    source_url: "https://www.maac.com/florida/tampa/maa-rocky-point/",
    first_seen_at: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    last_seen_at: new Date(now.getTime() - 1000 * 60 * 60 * 1).toISOString(),
    last_price_change_at: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: 103,
    unit_number: "T-108",
    floor_plan_id: 3,
    composite_key: "traditional-3x2.5-1552_3_2.5_1552_t-108",
    beds: 3,
    baths: 2.5,
    sq_ft: 1552,
    floor: 1,
    current_price: 3240,
    price_min: 3120,
    price_max: 3490,
    is_available: true,
    available_date: "Available Now",
    move_in_special: "Waived app + admin fees",
    lease_terms: "12-15 months",
    has_garage: true,
    has_fireplace: false,
    has_smart_home: true,
    is_renovated: false,
    is_top_floor: false,
    is_end_unit: true,
    has_sunroom: true,
    has_balcony: true,
    has_washer_dryer: true,
    view_type: "bay",
    feature_tags: ["Attached Garage", "Bay View", "End Unit", "Boat Slip"],
    description: "Townhome with attached garage and bay-facing windows.",
    source: "apartments_com",
    source_url: "https://www.apartments.com/maa-rocky-point-tampa-fl/7wemg5w/",
    first_seen_at: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    last_seen_at: new Date(now.getTime() - 1000 * 60 * 60 * 2).toISOString(),
    last_price_change_at: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
];

export const images: ImageAsset[] = [
  {
    id: 1,
    apartment_id: 101,
    image_type: "unit_photo",
    source_url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    public_url:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    sort_order: 0,
    alt_text: "Living room with natural lighting",
  },
  {
    id: 2,
    apartment_id: 102,
    image_type: "unit_photo",
    source_url: "https://images.unsplash.com/photo-1493666438817-866a91353ca9",
    public_url:
      "https://images.unsplash.com/photo-1493666438817-866a91353ca9?auto=format&fit=crop&w=1200&q=80",
    sort_order: 0,
    alt_text: "Renovated kitchen",
  },
  {
    id: 3,
    apartment_id: 103,
    image_type: "unit_photo",
    source_url: "https://images.unsplash.com/photo-1560448204-603b3fc33ddc",
    public_url:
      "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?auto=format&fit=crop&w=1200&q=80",
    sort_order: 0,
    alt_text: "Townhome-style living room",
  },
];

export const priceHistory: PriceHistoryPoint[] = [
  { apartment_id: 101, date: "2026-01-15", price: 1920 },
  { apartment_id: 101, date: "2026-01-24", price: 1880 },
  { apartment_id: 101, date: "2026-02-01", price: 1820, special: "6 weeks free" },
  { apartment_id: 102, date: "2026-01-20", price: 1720 },
  { apartment_id: 102, date: "2026-01-28", price: 1690 },
  { apartment_id: 102, date: "2026-02-05", price: 1685 },
  { apartment_id: 103, date: "2026-01-10", price: 3490 },
  { apartment_id: 103, date: "2026-01-26", price: 3325 },
  { apartment_id: 103, date: "2026-02-06", price: 3240 },
];

export const scrapeLogs: ScrapeLog[] = [
  {
    id: 1,
    started_at: new Date(now.getTime() - 1000 * 60 * 90).toISOString(),
    completed_at: new Date(now.getTime() - 1000 * 60 * 84).toISOString(),
    source: "maa",
    status: "success",
    units_found: 47,
    new_units: 1,
    price_changes: 3,
    duration_seconds: 344,
  },
  {
    id: 2,
    started_at: new Date(now.getTime() - 1000 * 60 * 88).toISOString(),
    completed_at: new Date(now.getTime() - 1000 * 60 * 83).toISOString(),
    source: "apartments_com",
    status: "partial",
    units_found: 33,
    new_units: 0,
    price_changes: 1,
    duration_seconds: 292,
    error_message: "Encountered anti-bot challenge on pagination page 2",
  },
];
